//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR_Tort.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CakeDecoration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CakeDecoration()
        {
            this.SpecificationCakeDecoration = new HashSet<SpecificationCakeDecoration>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
        public string Name { get; set; }
        public int UnitId { get; set; }
        public int Amount { get; set; }
        public int TypeId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Weight { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    
        public virtual CakeDecorationType CakeDecorationType { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecificationCakeDecoration> SpecificationCakeDecoration { get; set; }
    }
}
