//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR_Tort.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingridient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingridient()
        {
            this.SpecificationIngridient = new HashSet<SpecificationIngridient>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
        public string Name { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> GostId { get; set; }
        public string Packing { get; set; }
        public string Characteristic { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Gost Gost { get; set; }
        public virtual IngridientType IngridientType { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecificationIngridient> SpecificationIngridient { get; set; }
    }
}
