//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR_Tort.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationOperation
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string Operation { get; set; }
        public int SerialNumber { get; set; }
        public int EquipmentTypeId { get; set; }
        public string TimeOnOperation { get; set; }
    
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual Product Product { get; set; }
    }
}
